<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_About_UserOptions</name>
   <tag></tag>
   <elementGuidId>7bd98b09-a581-4507-9249-98e7ecf2d9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'About')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(contains(text(), 'About') or contains(., 'About'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc703565-e556-4aff-a0a4-a307bc939cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>387ec483-11e7-4125-a860-4fc46b84985c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
