<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobMonitoring-JobDetailsPage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>81a79543-0271-4986-a321-210a6d9a38ed</testSuiteGuid>
   <testCaseLink>
      <guid>09316c6a-4551-4de4-894d-ce7fec709bad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/Pre-Req-Script-For-JobMonitoring-Ops</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07e6f513-a04f-4fe3-b70a-198f3f69be18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64007784-bca4-488a-8a51-9d250067468a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c87bd78-81b1-402b-ae17-375332c5d79c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1d0a01-35b1-4e4d-b5c8-bb176ad9c1bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f94f9b9-3a18-4eca-b080-5ff2e6edd9b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1c12b7f-deff-4bfd-b652-c2cc17ec0237</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46169b3c-0cd6-4158-a8ce-7add6dfb4583</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/Jobdetailspage_context menu</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c527aaac-1585-4a91-9518-435233c53e79</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1-12</value>
         </iterationEntity>
         <testDataId>Data Files/Sanity/TestDataForJobDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c527aaac-1585-4a91-9518-435233c53e79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobState</value>
         <variableId>4a636c84-6f6f-4327-bc88-0f06ed57c48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c527aaac-1585-4a91-9518-435233c53e79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobAction</value>
         <variableId>b07c6840-6124-403c-88c8-73fd685aac37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c527aaac-1585-4a91-9518-435233c53e79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>95be6fc3-cb4f-4e7e-aee7-4913d254fd84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c527aaac-1585-4a91-9518-435233c53e79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>aa175b05-32fc-49ca-a330-8cfe38b2837c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>398a9de1-bbd0-4375-83b0-afb0dbaf9ed9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Custom_actions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36613ca7-02ff-44ad-a63a-66d42a1fca50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edbdda98-3662-45dc-9cca-c374182f15b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcf0e7a0-7023-48e3-898b-b910e4b1c26b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/RunningFolder_jobspage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5912aa-44cb-4a2a-8cbd-d878986a8cb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3dfb89e-d66e-42d0-bfd7-4bbd555d0c58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b559ba8-93b4-4f35-8694-c51dea26e300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098e6013-1c93-4f47-8b26-69214f7e665a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>664f26e5-d7a9-47be-8ee3-4b510c72d42d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/Jobdetailspage_topmenu_icons</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2417b46e-35da-4aea-9aaa-e52ded1d719a</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>13-17</value>
         </iterationEntity>
         <testDataId>Data Files/Sanity/TestDataForJobDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2417b46e-35da-4aea-9aaa-e52ded1d719a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobState</value>
         <variableId>2db3f3fe-0e4e-4a05-b27b-4c5ca2494e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2417b46e-35da-4aea-9aaa-e52ded1d719a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobAction</value>
         <variableId>5aaa9923-e80c-4ae0-961d-4d51951fd51f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2417b46e-35da-4aea-9aaa-e52ded1d719a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>ca86eeef-baa8-4163-8371-d8cb9e9455af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2417b46e-35da-4aea-9aaa-e52ded1d719a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>fb69884b-d493-49b8-9b33-2dcf82799a23</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
